databases:
  - name: Budget
    databaseName: budget_oy89
    user: budget_oy89_user

services:
  - type: web
    name: Budgeting
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_oy89
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false